"""updated primary id and organization id int to uuid type dashboard model

Revision ID: 9620437d2576
Revises: 6d6684d697ce
Create Date: 2026-09-06 10:17:38.603242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9620437d2576'
down_revision: Union[str, Sequence[str], None] = '6d6684d697ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE dashboards ALTER COLUMN id DROP DEFAULT')
    op.alter_column('dashboards', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               postgresql_using="('00000000-0000-0000-0000-' || lpad(to_hex(id), 12, '0'))::uuid",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE dashboards ALTER COLUMN id DROP DEFAULT')
    op.alter_column('dashboards', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               postgresql_using="(('x' || right(replace(id::text, '-', ''), 12))::bit(48)::bigint)::integer",
               existing_nullable=False)
    # ### end Alembic commands ###
