"""Added question model

Revision ID: c6697b88c238
Revises: 499dd42203d7
Create Date: 2026-09-02 06:17:50.931841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6697b88c238'
down_revision: Union[str, Sequence[str], None] = '499dd42203d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('query_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visualization', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_created_by'), 'questions', ['created_by'], unique=False)

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'data_source_type') THEN
                CREATE TYPE data_source_type AS ENUM ('BIGQUERY', 'POSTGRES', 'MYSQL', 'SNOWFLAKE', 'REDSHIFT');
            END IF;
        END $$;
        """
    )

    op.alter_column('data_sources', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('BIGQUERY', 'POSTGRES', 'MYSQL', 'SNOWFLAKE', 'REDSHIFT', name='data_source_type'),
               existing_nullable=False,
               postgresql_using='type::data_source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_sources', 'type',
               existing_type=sa.Enum('BIGQUERY', 'POSTGRES', 'MYSQL', 'SNOWFLAKE', 'REDSHIFT', name='data_source_type'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using='type::varchar')
    op.execute("DROP TYPE IF EXISTS data_source_type")
    op.drop_index(op.f('ix_questions_created_by'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
